name: Build and Upload to itch.io

on:
  push:
    branches:
      - itch
  workflow_dispatch:    # Allow manual trigger

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags
    
    - name: Zip Repository
      run: |
        zip -r augame.zip .
    
    - name: Upload to itch.io
      env:
        BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
      run: |
        curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
        unzip butler.zip
        chmod +x butler
        ./butler push augame.zip aurob/augame:main
